name: flutter_cache_strategy
description: A package to implement a complete caching strategy to handle the display of data for your users.
version: 1.0.0+1
repository: https://github.com/romgrm/flutter_cache_strategy
homepage: https://github.com/romgrm/flutter_cache_strategy

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  http: ^0.13.5
  path_provider_platform_interface: ^2.0.6
  plugin_platform_interface: ^2.1.4

flutter:
